/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iocoder
 */

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class MainWindow extends javax.swing.JFrame {
    
    public static JExtPanel drawingArea;
    private static JColorChooser colorSel;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colors = new javax.swing.JColorChooser();
        tlbStandard = new javax.swing.JToolBar();
        butNew = new javax.swing.JButton();
        butOpen = new javax.swing.JButton();
        butSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        butUndo = new javax.swing.JButton();
        butRedo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        butSelect = new javax.swing.JButton();
        butFill = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        butAbout = new javax.swing.JButton();
        drawingParent = new javax.swing.JPanel();
        buttonPane = new javax.swing.JPanel();
        menuMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Belletto 1.01");

        colors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tlbStandard.setFloatable(false);
        tlbStandard.setRollover(true);

        butNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-new.png"))); // NOI18N
        butNew.setText("New");
        butNew.setFocusable(false);
        butNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbStandard.add(butNew);

        butOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-open.png"))); // NOI18N
        butOpen.setText("Open");
        butOpen.setFocusable(false);
        butOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbStandard.add(butOpen);

        butSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document-save.png"))); // NOI18N
        butSave.setText("Save");
        butSave.setFocusable(false);
        butSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbStandard.add(butSave);
        tlbStandard.add(jSeparator1);

        butUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        butUndo.setText("Undo");
        butUndo.setFocusable(false);
        butUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbStandard.add(butUndo);

        butRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redo.png"))); // NOI18N
        butRedo.setText("Redo");
        butRedo.setFocusable(false);
        butRedo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butRedo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbStandard.add(butRedo);
        tlbStandard.add(jSeparator2);

        butSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drag-arrow.png"))); // NOI18N
        butSelect.setText("Select");
        butSelect.setFocusable(false);
        butSelect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butSelect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSelectActionPerformed(evt);
            }
        });
        tlbStandard.add(butSelect);

        butFill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fill.png"))); // NOI18N
        butFill.setText("Fill");
        butFill.setFocusable(false);
        butFill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butFill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFillActionPerformed(evt);
            }
        });
        tlbStandard.add(butFill);
        tlbStandard.add(jSeparator3);

        butAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png"))); // NOI18N
        butAbout.setText("About");
        butAbout.setFocusable(false);
        butAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbStandard.add(butAbout);

        drawingParent.setBackground(new java.awt.Color(255, 255, 255));
        drawingParent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout drawingParentLayout = new javax.swing.GroupLayout(drawingParent);
        drawingParent.setLayout(drawingParentLayout);
        drawingParentLayout.setHorizontalGroup(
            drawingParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );
        drawingParentLayout.setVerticalGroup(
            drawingParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttonPaneLayout = new javax.swing.GroupLayout(buttonPane);
        buttonPane.setLayout(buttonPaneLayout);
        buttonPaneLayout.setHorizontalGroup(
            buttonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        buttonPaneLayout.setVerticalGroup(
            buttonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        menuMain.add(jMenu1);

        jMenu2.setText("Edit");
        menuMain.add(jMenu2);

        jMenu3.setText("Help");
        menuMain.add(jMenu3);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colors, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
            .addComponent(tlbStandard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawingParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tlbStandard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 158, Short.MAX_VALUE))
                    .addComponent(drawingParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colors, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSelectActionPerformed
        
        for(MouseListener ml : drawingArea.getMouseListeners())
            drawingArea.removeMouseListener(ml);
        
        for(MouseMotionListener mml : drawingArea.getMouseMotionListeners())
            drawingArea.removeMouseMotionListener(mml);
        
        drawingArea.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        
        drawingArea.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                
            }
            @Override
            public void mouseReleased(MouseEvent evt) {
                Shapes.unselectAll();
                Pixel point = new Pixel(evt.getX(), evt.getY());
                for(int i = Shapes.arr.size()-1; i >= 0; i--) {
                    if (Shapes.arr.get(i).contains(point)) {
                        Shapes.arr.get(i).select();
                        Shapes.selectedShapes.add(Shapes.arr.get(i));
                        break;
                    }
                }
                drawingArea.repaint();
                
            }
        });
        drawingArea.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                
            }
        });
        
    }//GEN-LAST:event_butSelectActionPerformed

    private void butFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFillActionPerformed
        
        Shapes.unselectAll();
        
        for(MouseListener ml : drawingArea.getMouseListeners())
            drawingArea.removeMouseListener(ml);
        
        for(MouseMotionListener mml : drawingArea.getMouseMotionListeners())
            drawingArea.removeMouseMotionListener(mml);
        
        drawingArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        drawingArea.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                
            }
            @Override
            public void mouseReleased(MouseEvent evt) {
                Pixel point = new Pixel(evt.getX(), evt.getY());
                for(int i = Shapes.arr.size()-1; i >= 0; i--) {
                    if (Shapes.arr.get(i).contains(point)) {
                        Shapes.arr.get(i).setColor(colorSel.getColor());
                        break;
                    }
                }
                drawingArea.repaint();
                
            }
        });
        drawingArea.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                
            }
        });
        
    }//GEN-LAST:event_butFillActionPerformed

    public static void addLibrary(Class someClass)
        throws InstantiationException, IllegalAccessException {
        Shapes.addButton(someClass.getName());
        Shapes.samples.add((Shape) someClass.newInstance());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                
                // the window
                MainWindow win = new MainWindow();
                
                // button pane:
                win.buttonPane.setLayout(new GridLayout(0, 1));
                
                // drawing area:
                drawingArea = new JExtPanel();
                win.drawingParent.setLayout(new GridLayout(0, 1));
                win.drawingParent.add(drawingArea);
                
                // color selector:
                colorSel = win.colors;
                colorSel.setPreviewPanel(new JPanel());
                
                // initialize shapes class:
                Shapes.initStuff(win.buttonPane, drawingArea, colorSel);
               
                // load libraries:
                try {
                    addLibrary(Line.class);
                    addLibrary(Ellipse.class);
                    addLibrary(Circle.class);
                    addLibrary(Rectangle.class);
                    addLibrary(Triangle.class);
                    addLibrary(Square.class);
                } catch (InstantiationException | IllegalAccessException e) {
                    // TODO: some error.
                    System.out.println("Exception: " + e);
                }
                
                // show window:
                win.setVisible(true);
                
                // buffers:
                win.createBufferStrategy(2);
                drawingArea.setDoubleBuffered(true);

            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAbout;
    private javax.swing.JButton butFill;
    private javax.swing.JButton butNew;
    private javax.swing.JButton butOpen;
    private javax.swing.JButton butRedo;
    private javax.swing.JButton butSave;
    private javax.swing.JButton butSelect;
    private javax.swing.JButton butUndo;
    private javax.swing.JPanel buttonPane;
    private javax.swing.JColorChooser colors;
    private javax.swing.JPanel drawingParent;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JToolBar tlbStandard;
    // End of variables declaration//GEN-END:variables
}
